### ISSUE TITLE
nginx.ng -- get() got an unexpected keyword argument 'merge'   

### ISSUE THREAD

**Issue by jlsphar** [saltstack-formulas/nginx-formula#38]
Ubuntu 14.04 with a fresh cloud.map deploy running the latest version of salt-minion 2014.1.5

```

---
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 263, in render_jinja_tmpl
    output = jinja_env.from_string(tmplstr).render(**unicode_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 5, in top-level template code
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 1013, in make_module
    return TemplateModule(self, self.new_context(vars, shared, locals))
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 1070, in __init__
    self._body_stream = list(template.root_render_func(context))
  File "/var/cache/salt/minion/files/base/nginx/ng/map.jinja", line 7, in top-level template code
    {% set nginx = salt['pillar.get']('nginx:ng', {
TypeError: get() got an unexpected keyword argument 'merge'


----------
    Rendering SLS "base:nginx.ng.vhosts" failed: Jinja error: get() got an unexpected keyword argument 'merge'
/var/cache/salt/minion/files/base/nginx/ng/map.jinja(7):

---
[...]
    {% for key, value in dict.items() %}
    - {{ key }}: {{ value|json() }}
    {% endfor %}
{% endmacro %}

{% set nginx = salt['pillar.get']('nginx:ng', {    <======================
    'lookup': salt['grains.filter_by']({
        'Debian': {
            'package': 'nginx',
            'service': 'nginx',
            'webuser': 'www-data',
[...]

---
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 263, in render_jinja_tmpl
    output = jinja_env.from_string(tmplstr).render(**unicode_context)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 5, in top-level template code
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 1013, in make_module
    return TemplateModule(self, self.new_context(vars, shared, locals))
  File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 1070, in __init__
    self._body_stream = list(template.root_render_func(context))
  File "/var/cache/salt/minion/files/base/nginx/ng/map.jinja", line 7, in top-level template code
    {% set nginx = salt['pillar.get']('nginx:ng', {
TypeError: get() got an unexpected keyword argument 'merge'
```

**Comment by quixoten** [comment]
I have run into this issue using `salt-ssh`. I'm invoking `salt-ssh` on an Archlinux box to configure an Ubuntu 14.04 virtual machine. Using the latest version of salt (version info below).

### Full output

```
archlinux$ salt-ssh '*' state.highstate
[CRITICAL] Rendering SLS 'base:salt.master' failed: Jinja error: get() got an unexpected keyword argument 'merge'
/tmp/.vagrant_1d5674__salt/running_data/var/cache/salt/minion/files/base/salt/map.jinja(71):
---
[...]
                'syndic_service': 'salt_syndic'},
}, merge=salt['pillar.get']('salt:lookup')) %}

{% do default_settings.salt.update(distro_map) %}

{% set salt_settings = salt['pillar.get']('salt', default=default_settings.salt,    <======================
  merge=True) %}
---
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 280, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 1, in top-level template code
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1013, in make_module
    return TemplateModule(self, self.new_context(vars, shared, locals))
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1070, in __init__
    self._body_stream = list(template.root_render_func(context))
  File "/tmp/.vagrant_1d5674__salt/running_data/var/cache/salt/minion/files/base/salt/map.jinja", line 71, in top-level template code
    {% set salt_settings = salt['pillar.get']('salt', default=default_settings.salt,
TypeError: get() got an unexpected keyword argument 'merge'


saltmaster1:
    - Rendering SLS 'base:salt.master' failed: Jinja error: get() got an unexpected keyword argument 'merge'
    - /tmp/.vagrant_1d5674__salt/running_data/var/cache/salt/minion/files/base/salt/map.jinja(71):
    - ---
    - [...]
    -                 'syndic_service': 'salt_syndic'},
    - }, merge=salt['pillar.get']('salt:lookup')) %}
    - 
    - {% do default_settings.salt.update(distro_map) %}
    - 
    - {% set salt_settings = salt['pillar.get']('salt', default=default_settings.salt,    <======================
    -   merge=True) %}
    - ---
    - Traceback (most recent call last):
    -   File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 280, in render_jinja_tmpl
    -     output = template.render(**decoded_context)
    -   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    -     return self.environment.handle_exception(exc_info, True)
    -   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    -     reraise(exc_type, exc_value, tb)
    -   File "<template>", line 1, in top-level template code
    -   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1013, in make_module
    -     return TemplateModule(self, self.new_context(vars, shared, locals))
    -   File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1070, in __init__
    -     self._body_stream = list(template.root_render_func(context))
    -   File "/tmp/.vagrant_1d5674__salt/running_data/var/cache/salt/minion/files/base/salt/map.jinja", line 71, in top-level template code
    -     {% set salt_settings = salt['pillar.get']('salt', default=default_settings.salt,
    - TypeError: get() got an unexpected keyword argument 'merge'
    - 
    -
```

### Version Info

```
archlinux$ salt --versions-report
           Salt: 2014.7.2
         Python: 2.7.9 (default, Dec 11 2014, 04:42:00)
         Jinja2: 2.7.3
       M2Crypto: 0.22
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.5.0
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed

ubuntu:/tmp/.vagrant_1d5674__salt$ python2.7 salt-call --versions-report
[CRITICAL] Unable to import msgpack or msgpack_pure python modules
           Salt: 2014.7.2
         Python: 2.7.6 (default, Mar 22 2014, 22:59:56)
         Jinja2: 2.7.3
       M2Crypto: Not Installed
 msgpack-python: Not Installed
   msgpack-pure: Not Installed
       pycrypto: Not Installed
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: Not Installed
           RAET: Not Installed
            ZMQ: Not Installed
           Mako: Not Installed
```

**Comment by quixoten** [comment]
Whoops, when I added my previous comment I assumed that this issue was on the salt project itself, as I suspect that's where the issue may be. I got this error using the salt-formula, not this nginx-formula. That being clarified, I think I'll create an issue against salt itself, but leave my comments here in place for now as this nginx-formula may have a similar issue with `salt-ssh`.

**Comment by noelmcloughlin** [comment]
See https://github.com/saltstack-formulas/nginx-formula/commit/f6ba9ddb59ec1feabed6a1b4230612bf7f6d3795
